### ISSUE TITLE
sphinx.ext.todo ベースで書式カスタマイズ可能な todo 拡張をつくる

### ISSUE THREAD

**Issue by shouh** [shouh/NWGI#8]
## 目的
元ネタ https://github.com/sphinx-doc/sphinx/issues/2730

ソースを提示いただいたので、これ理解して作ってみる。

## 情報源
* https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/todo.py

## アドバイス和訳
> sphinx.ext.todo is consist of nodes, directives, config values, writers and event handlers (You can see them in sphinx/ext/todo.py). And you can replace one of them in your extension. so you can customize the output format with replacing writers like following:

todo 拡張は nodes, directives, ... 等の部品から構成されてるよ。部品の一部を自作拡張内で置き換えてやれば改造できるよ。（改造のポテンシャルは君の力次第だけど一般的な力があれば）出力フォーマットを変えることもできるよ。ちなみに Writer ね。

## わからんこととか
* [x] 自作した拡張やどうやって sphinx に組み込むの？
* [x] 組み込んだ拡張はどうやって使用するの？
* [x] todo の書式は `課題: ...` となってるけど、この **「課題」** の部分はどこをいじれば変えられるの？
  * 見た感じソースに直接書いてあるわけではない。localize されてるのかな？
* [x] todolist では `(元のエントリ は、 c:\....rst の n 行目です)` という表記も出るけど、この部分もどこいじれば変えられるの？

## :x: 見解
ポテンシャルが無くて不可能。

ただしソースを精読すれば、ポテンシャルがある or 抜け道があることがわかるかもしれない。精読できれば。

**Comment by shouh** [comment]
## メモ
肝はここっぽいな。

```python
def my_visit_todo_node(self, node):
    self.body.append('<div style="border-style: solid; border-color: red;">')

def my_depart_todo_node(self, node):
    self.body.append('</div>')

...

    app.add_node(todo_node,
                 html=(my_visit_todo_node, my_depart_todo_node),
```

html の時だけ my 出力フォーマット設定を使うぜって感じかな。ここでは red solid border で囲むようにしてる。

**Comment by shouh** [comment]
# 「課題」や「元のエントリ」の文字列
## どこにある？
「課題」は https://github.com/sphinx-doc/sphinx/blob/174e61fdb2fef4859b0b93abc139675f0e25dda5/sphinx/locale/ja/LC_MESSAGES/sphinx.po の 472-474 行目。

```
#: sphinx/ext/todo.py:56
msgid "Todo"
msgstr "課題"
```

「元のエントリ」は https://github.com/sphinx-doc/sphinx/blob/174e61fdb2fef4859b0b93abc139675f0e25dda5/sphinx/locale/ja/LC_MESSAGES/sphinx.po の
480-483 行目。

```
#: sphinx/ext/todo.py:132
#, python-format
msgid "(The <<original entry>> is located in %s, line %d.)"
msgstr "(<<元のエントリ>> は、 %s の %d 行目です)"
```

## 呼び出し元はどうなってる？
「課題」

```python
    def run(self):
        if not self.options.get('class'):
            self.options['class'] = ['admonition-todo']

        (todo,) = super(Todo, self).run()
        if isinstance(todo, nodes.system_message):
            return [todo]

        todo.insert(0, nodes.title(text=_('Todo'))) # <==== ここっすわ！
        set_source_info(self, todo)
```

「元のエントリ」

```python
        for todo_info in env.todo_all_todos:
            para = nodes.paragraph(classes=['todo-source'])
            if app.config['todo_link_only']:
                description = _('<<original entry>>')  # <---- ここやね。
            else:
                description = (
                    _('(The <<original entry>> is located in %s, line %d.)') %
                    (todo_info['source'], todo_info['lineno'])
                )
            desc1 = description[:description.find('<<')]
            desc2 = description[description.find('>>')+2:]
para += nodes.Text(desc1, desc1)
```
## つまり「課題」を変えたいなら？
愚直にやるならこうだな。

```python
        todo_title_text = 'TODO'
        todo.insert(0, nodes.title(text=todo_title_text))
```

po ファイルに基づいたローカライズに従うなら‥どうやるんだろ。po ファイルにも sphinx 拡張的な仕組みはあるのかね？

## で、po ファイルって何だ？
Babel で作った出力ファイルかな？

[pybabelコマンドを使ってアプリケーションを国際化する - スコトプリゴニエフスク通信](http://perezvon.hatenablog.com/entry/20070709/1183996523) でも出力が po ファイルになってる。

## つまり po ファイルいじれば変えられるの？
どうだろ。sphinx が po ファイルをどのタイミングで読んでるのか、そもそもどう取り込んでるのかがわからんのでなんとも言えない。毎回律儀に read してるなら、po ファイルいじればいけるはずだけど、たぶんそうじゃない。

うちの sphinx はバイナリで存在してるんで、po ファイルの解釈もこの中に入ってる。ってことは編集はできない。……うん **po ファイルの編集は無理** 。

**Comment by shouh** [comment]
## Sphinx 拡張についてお勉強するぜい
ネタはこれな http://docs.sphinx-users.jp/extensions.html

> たとえば、作った拡張機能がfoo.pyという名前で、プロジェクトルートの下のextsフォルダに置かれていた場合には、 conf.py の中に以下のように記述します

つまりプロジェクト中の適当なディレクトリ配下に適当な書式で書いた hoge.py 置いてビルドしてやるだけで、もう拡張が使える……って感じなのかな。（あと conf.py に include 的な表記も必要なんだろうけど）。

### 例1: sphinxcontrib-disqus
https://github.com/Robpol86/sphinxcontrib-disqus

conf.py に discus 系パラメータを定義しておくことと、disqus フォーム埋め込みたいところで `.. disqus::` を記述すること、の二つ。

* :question: ` ..disqus::` と書いたとき、sphinx  はどんな風に解釈する？
  * A: 見た感じ、`..foo::` があれば foo.py を解釈する、というふうに読めるぜ？
    * つまり自作の todo 拡張作って、その名前が unkotodo.py だとするなら、本文には `.. unkotodo::` と書けばいいというイメージかな

**Comment by shouh** [comment]
## tk0miya さんサンプル動かしてみる
### try1
まず俺の sphinx プロジェクトはこうなってる。

```
$ cd C:\work\hoge_document\source
$ ls
_static
_template
conf.py
index.rst
sec1.rst
sec2.rst
```

これに対して、以下のように変更を加えてみた。

```
$ cd
C:\work\hoge_document\source
$ ls
_ext  # <-- これ作った
conf.py
mytodo_user.rst # <-- ここに .. mytodo:: を記述した
```

ちなみに `_ext` フォルダの中には、tk0miya さんサンプルの内容まんま(utf-8 の shibang 書いたけど)を `mytodo.py` って名前で保存。あと空ファイルの `__init__.py` もつくった。

ちなみにちなみに conf.py には以下を追加した。

```python
# -- My extensions --------------------------------------------------------

sys.path.append(os.path.abspath('_ext'))
extensions = ['mytodo']
```

これでビルドしてみて、エラー無く通ったのだが、生成された HTML には mytodo のコンテンツがどこにも表示されてない。

……あー、違うわ。エラー出てるわ（ **二回目以降エラーが出なくなるから気づかなかった** )。

```
C:\work\hoge_document\source\mytodo_user.rst:7: ERROR: Unknown directive type "mytodo".
```

なるほど。まだ認識されてないのか。どこがおかしいんぞ？

### try2
`__init__.py` の内容を、disqus 拡張のまんまに書いてみた。意味はわかってないのでおまじない。

```
"""Declare namespace."""

__import__('pkg_resources').declare_namespace(__name__)
```

効果無し。

### try3: 
directive がちゃんと追加されるようにすればいいと、 http://docs.sphinx-users.jp/extdev/tutorial.html#build-phases 見て読めたんで、試す。

before

```
    app.add_directive('todo', Todo)
    app.add_directive('todolist', TodoList)
```

after

```
    app.add_directive('mytodo', Todo)
    app.add_directive('mytodolist', TodoList)
```

……効果なし。まだ同じエラーが出る。

### try4
* :question: conf.py の sys.path にちゃんと追加されてないないじゃね？
  * A: いいえ、追加されてます。print sys.path で試して、結果を念のためファイル名指定実行に貼り付けてそのまま開けたことを確認しました。

### try5
ちょｗｗｗ 

```python
# -- My extensions --------------------------------------------------------

sys.path.append(os.path.abspath('_ext'))
extensions = ['mytodo']

...

extensions = [
    'sphinx.ext.todo',
]
```

こうなってた。そりゃ上書きされて無効化されるわよね。

なのでこうした

```python
sys.path.append(os.path.abspath('_ext'))
extensions.append('mytodo')
```

……別のエラーや。

```
$ make html
Running Sphinx v1.3.1

Extension error:
Config value 'todo_include_todos' already present
```

どうも `sphinx.ext.todo` と Config value とやらを共有しちゃってるのがダメみたい（多重定義になってる）。

### try6
mytodo.py をこうした。

```python
def setup(app):
    # app.add_config_value('todo_include_todos', False, 'html') # コメントアウトしたのよ
    app.add_config_value('todo_link_only', False, 'html')
```

これでビルド通って tk0miya さんサンプル動いたぜ。赤線で囲まれた todo が出来上がり。

けどまだ :x: やわ。 **sphinx.ext.todo の書式も変わってるごゴルァ**

……なんかいろいろ設定が共有されてるっぽいねー。こりゃ tk0miya さんサンプル本来通りに mytodo じゃなくて todo にして、元の sphinx.ext.todo を extensions から外す……のほうが賢いかも。

ともあれ拡張の作り方はわかった。

**Comment by shouh** [comment]
## 結論: たぶん無理
俺がやるべきなのは、本質的にいえば 「sphinx.ext.todo に元から備わってる、課題文字列や元のエントリ文字列を生成するプロセスについて、そのプロセスに入る前に、そのプロセスが使用する該当変数の値を、外部(独自拡張)から書き換えられるかどうか」ってこと。

もっといえば、その「そのプロセスが使用する該当変数の値」が、「外部から俺を書き換えてもいいですよ」という口を持っていて、かつその口に外部からアクセスできるようになっているかどうかという話に帰着される。

「課題」文字列を例にすると、

``` python
        todo.insert(0, nodes.title(text=_('Todo')))
        # ここ以降で nodes.title の値を「独自拡張から」変えることができるか？
        # という話。
        set_source_info(self, todo)
```

たぶん無理だよね。独自拡張はフレームワーク的なものであって、 nodes という内部事情を直接編集する能力はないでしょう、たぶん。……まあ全部厳密に把握できたわけじゃない（しできるはずもない。それができるなら俺はもっとエンジニアやってる）けど。
